name: rosemusic
base: core24
version: '2.0.0'
summary: Listen To Online Radio # 79 char long summary
description: |
  Listen to online radio stations from around the world. This app is a simple radio player that allows you to listen to a variety of online radio stations on any device.
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  #riscv64:
  #  build-on: [riscv64]
  #  build-for: [riscv64]

apps:
  rosary:
    command: bin/rosary-music
    desktop: usr/share/applications/Rosary-Music.desktop

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  prep:
    plugin: dump
    build-snaps:
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential 
      - curl 
      - wget 
      - file 
      - libxdo-dev 
      - libssl-dev 
      - libayatana-appindicator3-dev 
      - librsvg2-dev
      - dpkg
      - yarn
    #  - npm
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libglu1-mesa
      - libsoup-3.0-0
      - freeglut3-dev
    source: https://github.com/RoseBlume/RoseMusic.git
      #- on amd64 to amd64: https://github.com/RoseBlume/RoseMusic/releases/download/v1.1.0/Rosary-Music_1.1.0_amd64.deb
      #- on arm64 to arm64: https://github.com/RoseBlume/RoseMusic/releases/download/v1.1.0/Rosary-Music_1.1.0_arm64.deb
    #  - on armhf to armhf: https://github.com/RoseBlume/RoseMusic/releases/download/v1.1.0/Rosary-Music_1.1.0_armel.deb
    #source-type: deb
    override-pull: |
      set -eu
      craftctl default
      rustup default stable
      yarn install
      yarn run tauri build -- -b deb
      dpkg-deb -x src-tauri/target/release/bundle/deb/*.deb here
    organize:
      here/usr/bin/rosary-music: bin/rosary-music
      here/usr/share/icons/hicolor/128x128/apps/rosary-music.png: /usr/share/icons/hicolor/128x128/apps/rosary-music.png
      here/usr/share/icons/hicolor/32x32/apps/rosary-music.png: /usr/share/icons/hicolor/32x32/apps/rosary-music.png
      here/usr/share/icons/hicolor/256x256@2/apps/rosary-music.png: /usr/share/icons/hicolor/256x256@2/apps/rosary-music.png