name: rosemusic
base: core24
version: '2.1.0'
summary: Listen To Online Radio # 79 char long summary
description: |
  Listen to online radio stations from around the world. This app is a simple radio player that allows you to listen to a variety of online radio stations on any device.
grade: stable
confinement: strict
adopt-info: prep
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  #riscv64:
  #  build-on: [riscv64]
  #  build-for: [riscv64]

apps:
  rosary:
    command: usr/bin/rosary-music
    desktop: usr/share/applications/Rosary-Music.desktop
    extensions: [gnome]
    plugs:
      - network

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  prep:
    plugin: dump
    parse-info: io.github.roseblume.rosemusic.metainfo.xml
    build-snaps:
      - rustup/latest/stable
      - node/20/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    #  - npm
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: https://github.com/RoseBlume/RoseMusic.git
      #- on amd64 to amd64: https://github.com/RoseBlume/RoseMusic/releases/download/v1.1.0/Rosary-Music_1.1.0_amd64.deb
      #- on arm64 to arm64: https://github.com/RoseBlume/RoseMusic/releases/download/v1.1.0/Rosary-Music_1.1.0_arm64.deb
    #  - on armhf to armhf: https://github.com/RoseBlume/RoseMusic/releases/download/v1.1.0/Rosary-Music_1.1.0_armel.deb
    #source-type: deb
    override-build: |
      set -eu
      rustup default stable
      yarn install
      yarn run tauri build -- -b deb
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
    #organize:
    #  here/usr/bin/rosary-music: bin/rosary-music
    #  here/usr/share/applications/Rosary-Music.desktop: usr/share/applications/rosarymusic.desktop
    #  here/usr/share/icons/hicolor/128x128/apps/rosary-music.png: usr/share/icons/hicolor/128x128/apps/rosary-music.png
    #  here/usr/share/icons/hicolor/32x32/apps/rosary-music.png: usr/share/icons/hicolor/32x32/apps/rosary-music.png
    #  here/usr/share/icons/hicolor/256x256@2/apps/rosary-music.png: usr/share/icons/hicolor/256x256@2/apps/rosary-music.png
